"""Helpers that generate Triton Inference Server configs for I3 models.

The I3 TCN encoder can be exported to ONNX (see
:mod:`i3.encoder.onnx_export`). This module produces the
``config.pbtxt`` file that Triton reads from the model repository at
``model_repository/tcn_encoder/config.pbtxt``.

The config enables:

* dynamic batching with preferred batch sizes ``[4, 8, 16]`` and a
  10 ms queue delay (``max_queue_delay_microseconds = 10_000``);
* separate CPU and GPU instance groups, so the same repository works on a
  laptop and on a GPU host;
* a versioned model directory at ``model_repository/tcn_encoder/1/model.onnx``.

Usage
-----

.. code-block:: python

    from pathlib import Path
    from i3.serving.triton_config import generate_triton_config

    generate_triton_config(Path("model_repository"), include_gpu=True)

The function also writes a top-level README for the repository to help
operators discover which models are present.

"""

from __future__ import annotations

import logging
from pathlib import Path

logger = logging.getLogger(__name__)


_TCN_CONFIG_TEMPLATE = """\
# Auto-generated by i3.serving.triton_config. Do not edit by hand.
#
# Triton Inference Server configuration for the I3 TCN encoder.
#   Input:  [batch, window=128, input_dim=32] float32
#   Output: [batch, embedding_dim=64] float32

name: "tcn_encoder"
platform: "onnxruntime_onnx"
max_batch_size: 32

input [
  {{
    name: "sequences"
    data_type: TYPE_FP32
    dims: [128, 32]
  }}
]

output [
  {{
    name: "embeddings"
    data_type: TYPE_FP32
    dims: [64]
  }}
]

dynamic_batching {{
  preferred_batch_size: [4, 8, 16]
  max_queue_delay_microseconds: 10000
}}

{instance_groups}

version_policy: {{ latest: {{ num_versions: 1 }} }}
"""


_CPU_INSTANCE_GROUP = """\
instance_group [
  {
    count: 1
    kind: KIND_CPU
  }
]
"""


_GPU_INSTANCE_GROUP = """\
instance_group [
  {
    count: 1
    kind: KIND_CPU
  },
  {
    count: 1
    kind: KIND_GPU
    gpus: [0]
  }
]
"""


_README_TEMPLATE = """\
# Triton Model Repository

This directory is consumed by NVIDIA Triton Inference Server. Each subfolder
is a model; the numeric subfolders inside each model are versions.

## Layout

```
model_repository/
  README.md
  tcn_encoder/
    config.pbtxt
    1/
      model.onnx
```

## Export

Generate the ONNX file with:

```bash
python -m i3.encoder.onnx_export --checkpoint models/encoder/best_model.pt \\
    --output model_repository/tcn_encoder/1/model.onnx
```

## Serve

```bash
docker compose -f deploy/serving/docker-compose.triton.yml up
```

## Regenerate config

```python
from pathlib import Path
from i3.serving.triton_config import generate_triton_config
generate_triton_config(Path("model_repository"), include_gpu=True)
```
"""


def _detect_gpu() -> bool:
    """Return ``True`` if CUDA is available in the current process.

    Returns:
        Whether at least one CUDA device is visible.
    """
    try:
        import torch

        return bool(torch.cuda.is_available())
    except ImportError:
        return False


def generate_triton_config(
    repository_root: Path,
    include_gpu: bool | None = None,
    overwrite: bool = True,
) -> Path:
    """Generate the Triton ``config.pbtxt`` for the TCN encoder.

    Args:
        repository_root: The Triton model repository directory. The
            function creates ``repository_root/tcn_encoder/1/`` (so the
            ONNX export can be dropped in alongside ``config.pbtxt``) and
            writes a top-level ``README.md``.
        include_gpu: If ``None``, auto-detect via torch.cuda. Otherwise
            force CPU-only or CPU+GPU instance groups.
        overwrite: If ``False`` and ``config.pbtxt`` already exists, leave
            it in place.

    Returns:
        The path to the written ``config.pbtxt``.
    """
    repository_root.mkdir(parents=True, exist_ok=True)
    model_dir = repository_root / "tcn_encoder"
    version_dir = model_dir / "1"
    version_dir.mkdir(parents=True, exist_ok=True)

    if include_gpu is None:
        include_gpu = _detect_gpu()
    instance_groups = _GPU_INSTANCE_GROUP if include_gpu else _CPU_INSTANCE_GROUP
    config_text = _TCN_CONFIG_TEMPLATE.format(instance_groups=instance_groups)

    config_path = model_dir / "config.pbtxt"
    if overwrite or not config_path.exists():
        config_path.write_text(config_text, encoding="utf-8")
        logger.info("Wrote Triton config to %s", config_path)
    else:
        logger.info("Leaving existing Triton config at %s", config_path)

    readme_path = repository_root / "README.md"
    if overwrite or not readme_path.exists():
        readme_path.write_text(_README_TEMPLATE, encoding="utf-8")
        logger.info("Wrote Triton repo README to %s", readme_path)

    return config_path


def main() -> None:
    """CLI: write the config to ``./model_repository``."""
    import argparse

    logging.basicConfig(level=logging.INFO)
    parser = argparse.ArgumentParser(description="Generate Triton config.pbtxt for the I3 TCN.")
    parser.add_argument("--repository", type=str, default="model_repository")
    parser.add_argument("--cpu-only", action="store_true")
    parser.add_argument("--no-overwrite", action="store_true")
    args = parser.parse_args()
    generate_triton_config(
        Path(args.repository),
        include_gpu=False if args.cpu_only else None,
        overwrite=not args.no_overwrite,
    )


if __name__ == "__main__":
    main()
